In [15]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [16]:
A = np.random.randn(7, 4) @ np.random.randn(4, 7) # singular matrix

In [17]:
U, S, VT = np.linalg.svd(A)

In [18]:
tolerance = np.finfo(float).eps * np.max(A.shape)

In [19]:
SI = np.zeros_like(S)
SI[S > tolerance] = 1/S[S > tolerance]

In [23]:
S = np.zeros_like(A)
np.fill_diagonal(S, SI)
AI = VT.T @ S @ U.T

In [24]:
ApinvNp = np.linalg.pinv(A)

In [25]:
print(np.round( ApinvNp - AI ,5))

[[-0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0.  0. -0.  0.]
 [-0. -0. -0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0. -0.  0.  0.]]
