In [ ]:
# A = V^-1 L V
# A^-1 = (V^-1 L V)^-1
# A^-1 = V^-1 L^-1 V
# Собстенные вектора: совпадают
# Собственные числа: 1 / L, поскольку L - диагональная матрица

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(5,5)
A = A.T@A

In [3]:
Ai = np.linalg.inv(A)

In [4]:
eigvals_A  = np.linalg.eig(A)[0]
eigvals_Ai = np.linalg.eig(Ai)[0]

In [5]:
print('Eigenvalues of A:')
print(np.sort(eigvals_A))

print(' ')
print('Eigenvalues of inv(A):')
print(np.sort(eigvals_Ai))

print(' ')
print('Reciprocal of evals of inv(A):')
print(np.sort(1/eigvals_Ai))

Eigenvalues of A:
[ 0.01812254  1.61048089  2.85234621  8.29662723 11.44359884]
 
Eigenvalues of inv(A):
[ 0.0873851   0.12053091  0.35058858  0.62093254 55.17988911]
 
Reciprocal of evals of inv(A):
[ 0.01812254  1.61048089  2.85234621  8.29662723 11.44359884]
