In [38]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

In [39]:
rank = 5
matrix = np.random.randn(rank, rank)

In [40]:
P, L, U = scipy.linalg.lu(matrix)
print(U)

[[ 1.33111746 -0.15987796 -0.1926976  -0.53430037  0.04539769]
 [ 0.         -1.47167625  0.14873372 -0.76855035 -0.22928234]
 [ 0.          0.         -1.04409314  0.27695561 -1.88061891]
 [ 0.          0.          0.         -0.8472326   1.91380564]
 [ 0.          0.          0.          0.         -0.56336994]]


In [41]:
det = 1
for i in range(rank):
    sum = 0
    for j in range(rank - i):
        col = i + j
        row = j
        sum += U[row, col]
    det *= sum
print(det)

-0.5572546247818104


In [42]:
det = 1
for i in range(rank):
    for j in range(rank):
        if i == j:
            det *= U[i, j]
print(det * np.linalg.det(P))

-0.9762571566620419


In [43]:
print(np.linalg.det(P))
print(np.diag(U))

-1.0
[ 1.33111746 -1.47167625 -1.04409314 -0.8472326  -0.56336994]


In [44]:
np.linalg.det(matrix)

-0.9762571566620418