In [12]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [13]:
R = np.array([[1, .2, .9], [.2, 1, .3], [.9, .3, 1]])
R

array([[1. , 0.2, 0.9],
       [0.2, 1. , 0.3],
       [0.9, 0.3, 1. ]])

In [14]:
L, V = np.linalg.eig(R)
L = np.diag(L)

In [15]:
X = np.random.randn(3, 10000)
X

array([[-0.17690558,  0.3487044 ,  0.40145807, ...,  0.00964419,
        -1.16238251,  2.09117238],
       [-1.37828518, -0.5431268 , -0.33080181, ...,  0.01929848,
        -0.68571837, -0.53632256],
       [-0.62607774, -0.91220229,  0.76546404, ...,  0.29046972,
        -0.8083181 , -1.06546776]])

In [16]:
Y = V @ np.sqrt(L) @ X
Y

array([[ 0.28721579, -0.46161608, -0.09655579, ...,  0.0664375 ,
         1.01450306, -2.13944667],
       [ 0.67176698,  0.65849107, -0.85552221, ..., -0.26192188,
         1.27407267, -0.01767122],
       [-0.23329452, -0.60172597, -0.33562994, ...,  0.04174557,
         0.83766458, -2.30152438]])

In [18]:
Y1 = Y.T @ V @ np.linalg.inv(np.sqrt(L))

In [21]:
print(np.round(np.corrcoef(Y1), 3))

[[ 1.     0.576  0.758 ...  0.114 -0.914  0.678]
 [ 0.576  1.    -0.097 ... -0.746 -0.858  0.991]
 [ 0.758 -0.097  1.    ...  0.735 -0.428  0.034]
 ...
 [ 0.114 -0.746  0.735 ...  1.     0.299 -0.653]
 [-0.914 -0.858 -0.428 ...  0.299  1.    -0.918]
 [ 0.678  0.991  0.034 ... -0.653 -0.918  1.   ]]
