In [1]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [8]:
M = np.diag(np.random.rand(4) * 5)
print(M)
print(np.diag(M))

[[0.36162629 0.         0.         0.        ]
 [0.         2.11818822 0.         0.        ]
 [0.         0.         1.49270129 0.        ]
 [0.         0.         0.         2.15780667]]
[0.36162629 2.11818822 1.49270129 2.15780667]


In [3]:
Q, _ = np.linalg.qr(np.random.randn(4, 4))
Q

array([[-0.81933501,  0.11937747, -0.54039827, -0.1496959 ],
       [-0.32195331, -0.85477573,  0.35465817, -0.19980514],
       [ 0.41121544, -0.49342497, -0.75998157,  0.09930598],
       [-0.2365123 , -0.10788543,  0.067936  ,  0.96322758]])

In [4]:
R = Q @ M @ Q.T
R

array([[ 1.67422916, -0.51238176,  1.33638632, -0.73341157],
       [-0.51238176,  1.10688664, -1.04383768, -0.74285251],
       [ 1.33638632, -1.04383768,  2.56474569,  0.22397952],
       [-0.73341157, -0.74285251,  0.22397952,  4.53181291]])

In [5]:
print(np.round(R - R.T, 5))

[[ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [ 0.  0.  0.  0.]
 [-0.  0.  0.  0.]]


In [6]:
print(np.sort(np.diag(M)))
print(np.sort(np.linalg.eig(R)[0]))

[0.48212428 0.59046424 3.98210921 4.82297666]
[0.48212428 0.59046424 3.98210921 4.82297666]
