In [36]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [37]:
M = np.array([[-1,1], [-1,2]])

In [38]:
vi = M.T @np.linalg.inv(M @ M.T)
vi

array([[-2.,  1.],
       [-1.,  1.]])

In [39]:
print(M @ vi)

[[1. 0.]
 [0. 1.]]


In [40]:
L, V = np.linalg.eig(M)
l = L[1]
v = V[:, [1]]
v

array([[-0.35682209],
       [-0.93417236]])

In [41]:
vPinv = np.linalg.pinv(v)

In [42]:
LHS = vPinv @ M @ v
RHS = l * vPinv @ v

print(LHS)
print(RHS)

[[1.61803399]]
[[1.61803399]]


In [43]:
LHS = M @ v @ vPinv
RHS = l * v @ vPinv

print(LHS)
print(RHS)

[[0.20601133 0.53934466]
 [0.53934466 1.41202266]]
[[0.20601133 0.53934466]
 [0.53934466 1.41202266]]
