In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg
from scipy.linalg import toeplitz

In [5]:
def matrix_is_sim(m):
    mt = m.T
    if len(m[0,:]) != len(m[:, 0]):
        return False
    for i in range(len(m[0,:])):
        for j in range(len(m[:, 0])):
            if m[j, i] != mt[j, i]:
                return False
    return True
#m = np.arange(15).reshape(3, 5)
m = np.array([ [1,2,3], [2,3,1], [3,1,2] ])
print(matrix_is_sim(m))


True


In [20]:
# create symmetric and nonsymmetric matrices
A = np.random.randn(4,4)
print(A)
AtA = (A + A.T) / 2 # additive method!
print(matrix_is_sim(AtA))

[[ 0.11876509 -0.60469388 -0.43027576  0.10098873]
 [-1.42458017 -1.00297693 -0.76580017  0.67009119]
 [ 1.76988664 -0.20543121 -0.79209258  0.92799765]
 [-1.26892369  0.09979385  0.02153996  0.50386214]]
True
