In [24]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [25]:
A = np.random.randint(-14, 15, (4, 4))

In [26]:
L, V = np.linalg.eig(A)
V = V * np.e
D = np.diag(L)
VI = np.linalg.inv(V)

In [27]:
print('Reconstructed minus original:')
print(np.round(V @ D @ VI - A, 3))

Reconstructed minus original:
[[ 0.+0.j  0.-0.j -0.+0.j -0.+0.j]
 [ 0.+0.j -0.+0.j  0.+0.j  0.+0.j]
 [-0.-0.j  0.-0.j  0.+0.j  0.-0.j]
 [-0.+0.j -0.-0.j  0.-0.j -0.-0.j]]


In [28]:
for i in range(A.shape[0]):
  norm = np.sqrt(np.sum(V[:,i]*np.conj(V[:,i])))
  print(f'Eigenvector {i} has norm {norm}')

Eigenvector 0 has norm (2.718281828459045+0j)
Eigenvector 1 has norm (2.7182818284590455+0j)
Eigenvector 2 has norm (2.718281828459045-2.5593969475168605e-18j)
Eigenvector 3 has norm (2.718281828459045+2.5593969475168605e-18j)


Шкалирование не имеет значения, поскольку при инвертировании матрицы скаляр номализуется

In [29]:
A = np.random.randint(-14, 15, (4, 4))
A = A.T @ A
A

array([[174, -53, 159, -12],
       [-53,  81, -44, 109],
       [159, -44, 190,  64],
       [-12, 109,  64, 276]])

In [30]:
L, V = np.linalg.eig(A)
V = V * np.pi
D = np.diag(L)
#VI = np.linalg.inv(V)
VI = V.T

In [31]:
print('Reconstructed minus original:')
print(np.round(V @ D @ VI - A, 3))

Reconstructed minus original:
[[1543.311 -470.089 1410.267 -106.435]
 [-470.089  718.438 -390.263  966.787]
 [1410.267 -390.263 1685.225  567.655]
 [-106.435  966.787  567.655 2448.011]]


In [32]:
for i in range(A.shape[0]):
  norm = np.sqrt(np.sum(V[:,i]*np.conj(V[:,i])))
  print(f'Eigenvector {i} has norm {norm}')

Eigenvector 0 has norm 3.141592653589793
Eigenvector 1 has norm 3.1415926535897936
Eigenvector 2 has norm 3.1415926535897927
Eigenvector 3 has norm 3.141592653589793


Шкалирование имеет значение, поскольку инвертирование матрицы заменено на транспонирование - не имеет эффекта нормализации