In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
lambdas = [1, 2, -3]
v1=np.array([4,5,1])
v2=np.array([-4,0,-4])
v3=np.array([1,3,2])

print(v1)
print(v2)
print(v3)

[4 5 1]
[-4  0 -4]
[1 3 2]


In [11]:
w = np.zeros(3)
print(w)

[0. 0. 0.]


In [14]:
for i in range(len(w)):
    w[i] = lambdas[0] * v1[i] + lambdas[1] * v2[i] + lambdas[2] * v3[i]
print(w)

[ -7.  -4. -13.]
