In [1]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

In [2]:
rank = 5
matrix = np.random.randn(rank, rank)

In [3]:
ATA = matrix.T @ matrix

In [4]:
P, L, U = scipy.linalg.lu(matrix)

In [5]:
UTLTLU = U.T @ L.T @ L @ U

In [6]:
print(ATA)
print(UTLTLU)

[[ 5.63860538 -1.46299897  4.49376017  1.59169445 -3.51573827]
 [-1.46299897  1.71397316 -0.3340811   1.92848827  0.20538739]
 [ 4.49376017 -0.3340811   7.96232421  3.13402397 -6.63413532]
 [ 1.59169445  1.92848827  3.13402397  5.04929536 -1.95787354]
 [-3.51573827  0.20538739 -6.63413532 -1.95787354  6.71945978]]
[[ 5.63860538 -1.46299897  4.49376017  1.59169445 -3.51573827]
 [-1.46299897  1.71397316 -0.3340811   1.92848827  0.20538739]
 [ 4.49376017 -0.3340811   7.96232421  3.13402397 -6.63413532]
 [ 1.59169445  1.92848827  3.13402397  5.04929536 -1.95787354]
 [-3.51573827  0.20538739 -6.63413532 -1.95787354  6.71945978]]


In [7]:
np.round( ATA - UTLTLU, 10)

array([[-0.,  0., -0.,  0.,  0.],
       [ 0., -0.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  0., -0.],
       [ 0., -0., -0.,  0.,  0.],
       [ 0., -0.,  0., -0.,  0.]])