In [8]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [9]:
R = np.array([[1, .2, .9], [.2, 1, .3], [.9, .3, 1]])
R

array([[1. , 0.2, 0.9],
       [0.2, 1. , 0.3],
       [0.9, 0.3, 1. ]])

In [10]:
X = np.random.randn(3, 10000)
X

array([[ 1.04550584,  0.12764769,  1.94517677, ..., -0.83845373,
         0.42512341,  1.92244707],
       [-1.07578135, -0.40525885,  0.05730505, ...,  0.44130391,
         0.37185529, -0.17862694],
       [ 2.60167087, -0.69460893, -0.49427379, ..., -0.52718163,
        -0.46428152,  1.49440874]])

In [11]:
L, V = np.linalg.eig(R)
L = np.diag(L)
print(L)
print(V)

[[2.02255456 0.         0.        ]
 [0.         0.09402458 0.        ]
 [0.         0.         0.88342086]]
[[-0.65954066 -0.69284486  0.29149978]
 [-0.32749414 -0.08419369 -0.94109458]
 [-0.67657498  0.71615461  0.17137347]]


In [12]:
Y = V @ np.sqrt(L) @ X
Y

array([[-0.03929856, -0.22394358, -1.9721256 , ...,  0.54825614,
        -0.60496097, -1.35581868],
       [-2.76045209,  0.56541926, -0.4702426 , ...,  0.84543037,
         0.20307356, -2.21263296],
       [-0.82316286, -0.3237006 , -1.9386831 , ...,  0.81875511,
        -0.40217992, -1.64829613]])

In [13]:
np.corrcoef(Y)

array([[1.        , 0.21419033, 0.9024671 ],
       [0.21419033, 1.        , 0.31286785],
       [0.9024671 , 0.31286785, 1.        ]])