In [1]:
import numpy as np

## Basic ML Homework
### Модуль 4: Теоретический минимум для ML: линейная алгебра, начала мат.анализа

## 1. Линейная алгебра

1.1 Даны матрицы $A = \begin{pmatrix}
2 & −4 \\
3 & 5 \\
−1 & 0 
\end{pmatrix},
$
$B = \begin{pmatrix}1 & 2 & 7 \\ −3 & −4 & 0 \\ 5 & 2 & 1 \end{pmatrix}$, $C = \begin{pmatrix}
6 & −3 & 9 \\
4 & −5 & 2 \\
8 & 1 & 5
\end{pmatrix}.$

Посчитайте матрицу $D = A^{\top}C - 2A^{\top}B^{\top}$. Приведите полную последовательность вычислений.

#### Решение:

$ \mathbf{A}^\intercal = \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix} $

$ \mathbf{B}^\intercal = \begin{pmatrix} 1 & -3 & 5 \\ 2 & -4 & 2 \\ 7 & 0 & 1 \end{pmatrix} $

$ \mathbf{D} = \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix} \cdot \begin{pmatrix} 6 & -3 & 9 \\ 4 & -5 & 2 \\ 8 & 1 & 5 \end{pmatrix} -
2 \cdot \begin{pmatrix} 2 & 3 & -1 \\ −4 & 5 & 0 \end{pmatrix} \cdot \begin{pmatrix} 1 & -3 & 5 \\ 2 & -4 & 2 \\ 7 & 0 & 1 \end{pmatrix} $

$ \mathbf{D} = \begin{pmatrix} 16 & -22 & 19 \\ −4 & -13 & -26 \end{pmatrix} -
2 \cdot \begin{pmatrix} 1 & -18 & 15 \\ 6 & -8 & -10 \end{pmatrix} $

$ \mathbf{D} = \begin{pmatrix} 16 & -22 & 19 \\ −4 & -13 & -26 \end{pmatrix} -
\begin{pmatrix} 2 & -36 & 30 \\ 12 & -16 & -20 \end{pmatrix} $

$ \mathbf{D} = \begin{pmatrix} 14 & 14 & -11 \\ −16 & 3 & -6 \end{pmatrix} $

#### Проверка:

In [ ]:
A = np.array((2, -4, 3, 5, -1, 0))
A = np.reshape(A, (3, 2))
A 

array([[ 2, -4],
       [ 3,  5],
       [-1,  0]])

In [ ]:
B = np.array((1, 2, 7, -3, -4, 0, 5, 2, 1))
B = np.reshape(B, (3, 3))
B

array([[ 1,  2,  7],
       [-3, -4,  0],
       [ 5,  2,  1]])

In [ ]:
C = np.array((6, -3, 9, 4, -5, 2, 8, 1, 5))
C = np.reshape(C, (3, 3))
C

array([[ 6, -3,  9],
       [ 4, -5,  2],
       [ 8,  1,  5]])

In [7]:
D = A.T @ C - 2 * A.T @ B.T
D

array([[ 14,  14, -11],
       [-16,   3,  -6]])

1.2 Дано:

$ 3 \cdot \begin{pmatrix} x & 2 & 3 \\ −1 & y & 4 \end{pmatrix} +
2 \cdot \begin{pmatrix} 1 & 2 & −5 \\ 2 & −6 & z \end{pmatrix} =
\begin{pmatrix}
8 & v & −1 \\
1 & 6 & 4 \end{pmatrix}. $

Найдите значения $x$, $y$, $z$, и $v$.

### Решение:

$ 3 \cdot \begin{pmatrix} x & 2 & 3 \\ −1 & y & 4 \end{pmatrix} +
2 \cdot \begin{pmatrix} 1 & 2 & −5 \\ 2 & −6 & z \end{pmatrix} -
\begin{pmatrix}
8 & v & −1 \\
1 & 6 & 4 \end{pmatrix} =
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \end{pmatrix} $

$ \begin{pmatrix} 3x + 2 - 8 & 6 + 4 - v & 9 - 10 + 1 \\ -3 + 4 - 1 & 3y - 12 - 6 & 12 + 2z - 4 \end{pmatrix} =
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \end{pmatrix} $

$ \begin{pmatrix} 3x - 6 & 10 - v & 0 \\ 0 & 3y - 18 & 2z + 8 \end{pmatrix} =
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \end{pmatrix} $

$ 
    \begin{aligned}
    &3x - 6 = 0 \\
    &10 - v = 0 \\
    &3y - 18 = 0 \\
    &2z + 8 = 0
    \end{aligned}
$

$ 
    \begin{aligned}
    &x = 2 \\
    &v = 10 \\
    &y = 6 \\
    &z = -4
    \end{aligned}
$

#### Проверка:

In [18]:
R = 3 * np.reshape(np.array((2, 2, 3, -1, 6, 4)), (2, 3)) + 2 * np.reshape(np.array((1, 2, -5, 2, -6, -4)), (2, 3)) - np.reshape(np.array((8, 10, -1, 1, 6, 4)), (2, 3))
R

array([[0, 0, 0],
       [0, 0, 0]])

1.3 На множестве $\mathbf{M}$ всех упорядоченных пар $(u; v)$ положительных чисел операции сложения и умножения введены
следующим образом:

$$
(u_1; v_1) + (u_2; v_2) = (u_1 \cdot u_2; v_1 \cdot v_2); 
λ(u; v) = (u^{\lambda}; v^{\lambda}),
$$

где $\lambda$ – вещественное число. Докажите, что при этом множество $\mathbf{M}$ становится линейным пространством. Выясните: а) какая пара играет роль нулевого элемента; б) какая пара является противоположной паре $(u; v)$; в) укажите размерность этого пространства и какой-нибудь его базис.

#### Доказательство:

##### Определение линейного пространства:

Множество $L$  называется линейным или векторным пространством, если для всех элементов (векторов) этого множества определены операции сложения и умножения на число и справедливо:
1. Каждой паре элементов $x$ и $y$ из $L$ отвечает элемент $x + y$ из $L$, называемый суммой $x$ и $y$, причём:
    1. $x + y = y + x$ − сложение коммутативно;
    2. $x + (y + z) = (x + y) + z$ − сложение ассоциативно;
    3. $x + 0 = x$ − существует единственный нейтральный элемент $0$ $( x + 0 = x$ для любого $x$ из $L)$;
    4. $x + (− x) = 0$ − для каждого элемента $x$ из $L$ существует единственный противоположный элемент $−x$ $( x + (−x) = 0$ для любого $x$ из $L)$.

2. Каждой паре $x$ и $α$, где $α$ − число, а $x$ элемент из $L$, отвечает элемент $α·x$, наываемый произведением $α$ и $x$, причём:
    1. $α·(β·x) = (α·β)·x$ − умножнение на число ассоциативно;
    2. $1·x = x$ − для любого элемента $x$ из $L$.
    
3. Операции сложения и умножения на число связаны соотношениями:
    1. $α·(x + y) = α·x + α·y$ − умножнение на число дистрибутивно относительно сложения элементов;
    2. $(α + β)·x = α·x + β·x$ − умножнение на вектор дистрибутивно относительно сложения чисел.

1.1. Коммутативность\
$
    \begin{aligned}
    (u_1;v_1) + (u_2;v_2) = (u_1 \cdot u_2; v_1 \cdot v_2) = (u_2 \cdot u_1; v_2 \cdot v_1) = (u_2;v_2) + (u_1;v_1) 
    \end{aligned}
$, поскольку элементарное умножение коммутативно

1.2. Ассоциативность\
$ (u_1;v_1) + ((u_2;v_2) + (u_3;v_3)) = (u_1;v_1) + (u_2 \cdot u_3; v_2 \cdot v_3) =  (u_1 \cdot u_2 \cdot u_3; v_1 \cdot v_2 \cdot v_3)$ $(1)$\
$ ((u_1;v_1) + (u_2;v_2)) + (u_3;v_3) = (u_1 \cdot u_2; v_1 \cdot v_2) + (u_3;v_3) =  (u_1 \cdot u_2 \cdot u_3; v_1 \cdot v_2 \cdot v_3)$ $(2)$\
$(1) = (2)$

1.3. Нейтральный элемент\
$ 0 = (1; 1)$\
$(u; v) + 0 = (u; v) + (1; 1) = (u \cdot 1; v \cdot 1) = (u; v)$

1.4. Противоположный элемент\
$ -(u; v) = (1 / u; 1 / v) $\
$(u; v) + (-(u; v)) = (u; v) + (1 / u; 1 / v) = (u / u; v / v) = (1; 1) = 0 $

1.4 Докажите, что множество всех квадратных матриц второго порядка с известными операциями сложения и умножения на число образуют четырехмерное линейное пространство. Укажите какой-нибудь базис этого пространства.

1.5 Укажите те значения параметров $p$ и $q$, при которых
ранг матрицы $A = \begin{pmatrix} 1 & 2 & 3 \\ 3 & 6 & p \\ 5 & 10 & q \end{pmatrix}$ равен единице.

#### Решение:

Ранг 1 матрицы A означает, что все столбцы можно выразить через один столбец. Таким столбцом является, например, первый столбец матрицы A. Приведённые ниже уравнения справедливы и для двух других столбцов, с соответствующими коэффициентами  

$ \lambda \cdot \begin{pmatrix} 1 \\ 3 \\ 5 \end{pmatrix} = \begin{pmatrix} 2 \\ 6 \\ 10 \end{pmatrix} \Rightarrow \lambda = 2 $

$ \lambda \cdot \begin{pmatrix} 1 \\ 3 \\ 5 \end{pmatrix} = \begin{pmatrix} 3 \\ p \\ q \end{pmatrix} \Rightarrow \lambda = 3$, при  $p = 9$ и $q = 15$

#### Проверка:

In [13]:
p = 9
q = 15

In [14]:
A = np.array((1, 2, 3, 3, 6, p, 5, 10, q))
A = np.reshape(A, (3, 3))
A

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [ 5, 10, 15]])

In [15]:
rank = np.linalg.matrix_rank(A)
rank

1

1.6 Относительно канонического базиса в $\mathbb{R}^2$ даны три вектора $f_1 = (2, −5)$, $f_2 = (−1, 3)$, $x = (1, −4)$. Докажите, что векторы $f_1$ и $f_2$ можно принять за новый базис, и найдите координаты вектора $x$ в этом базисе

1.7 Предположим, что существует линейный оператор, выраженный в базисе $(e_1, e_2)$ в виде матрицы $A = \begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}$. Найдите матрицу данного оператора в базисе из векторов $(\tilde{e}_1, \tilde{e}_2)$, если:

$$
\begin{cases}
\tilde{e}_1 = -2e_1 + 5e_2 \\
\tilde{e}_2 = -e_1 + 2e_2
\end{cases}.
$$

## 2. Начала математического анализа

1. Найти матрицу Гессе следующей функции:
$$
    f(x,y) = x^3 - 2xy + y^2 - 3x - 2y.
$$

    Доп.задание (явно в курсе не обсуждалось): найдите точки локального экстремума функции $f$.

2. Проверьте, что функция $f = \ln(\sqrt{x} + \sqrt{y})$ удовлетворяет уравнению:

$$
x \frac{\partial f}{\partial x} + y \frac{\partial f}{\partial y} = \frac{1}{2}.
$$

3. Используя правило для вычисления производной сложной функции, найдите полный дифференциал $\frac{df}{dt}$, если $$f = e^{xy}\ln(x+y), \quad x = 2t^2, \quad y = 1 - 2t^2 .$$

4. Предположим, задана функция $f: \mathbb{R}^3 \rightarrow \mathbb{R}^2$

$$
    f(x,y,z) = (x+y+z, xyz).
$$

   Найдите матрицу Якоби функции $f$, и её численное значение в точке $v = (1, 2, 3)$.