In [10]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [11]:
rank = 5
A = np.random.randn(rank, rank)
A = A.T @ A
A

array([[ 7.52636313, -2.51627842,  1.34279177, -3.52701667,  0.65793514],
       [-2.51627842,  6.34069809, -2.11059529,  2.37527242, -1.53315729],
       [ 1.34279177, -2.11059529,  8.01999895,  2.31732589, -0.99824237],
       [-3.52701667,  2.37527242,  2.31732589,  4.25992632, -1.19903555],
       [ 0.65793514, -1.53315729, -0.99824237, -1.19903555,  2.99411903]])

In [12]:
L, V = np.linalg.eig(A)
V

array([[-0.66733695,  0.07022695,  0.62654442,  0.35416103,  0.1781618 ],
       [ 0.55580877,  0.11813561,  0.667796  , -0.33231768,  0.34746807],
       [-0.21463043, -0.87562486,  0.06127114, -0.4067337 ,  0.13426998],
       [ 0.41440043, -0.42202931, -0.01506621,  0.768268  ,  0.24433753],
       [-0.16716481,  0.19048495, -0.3968746 , -0.09201577,  0.87737966]])

In [13]:
LS  = np.argsort(L)[::-1]
L = L[LS]
V = V[:,LS]

In [14]:
U, S, VT = np.linalg.svd(A)
VT

array([[-0.66733695,  0.55580877, -0.21463043,  0.41440043, -0.16716481],
       [-0.07022695, -0.11813561,  0.87562486,  0.42202931, -0.19048495],
       [-0.62654442, -0.667796  , -0.06127114,  0.01506621,  0.3968746 ],
       [-0.1781618 , -0.34746807, -0.13426998, -0.24433753, -0.87737966],
       [-0.35416103,  0.33231768,  0.4067337 , -0.768268  ,  0.09201577]])

In [15]:
print('Eigenvalues and singular values:')
print(np.vstack((L, S)).T)


Eigenvalues and singular values:
[[12.40898561 12.40898561]
 [ 9.5311094   9.5311094 ]
 [ 4.64378177  4.64378177]
 [ 2.03386465  2.03386465]
 [ 0.52336409  0.52336409]]


In [16]:
print(f'\nLeft-Right singular vectors (should be zeros)')
print(np.round(U - VT.T, 10))


Left-Right singular vectors (should be zeros)
[[ 0. -0. -0. -0. -0.]
 [ 0. -0. -0. -0.  0.]
 [ 0.  0. -0. -0. -0.]
 [-0.  0.  0. -0. -0.]
 [-0.  0.  0. -0.  0.]]


In [17]:
print(f'\nSingular vectors - eigenvectors (should be zeros)')
print(np.round(U - V, 10)) # subtract and 
print(' ')                  
print(np.round(U + V, 10)) # add for sign indeterminancy


Singular vectors - eigenvectors (should be zeros)
[[ 0.         -0.1404539  -1.25308884 -0.3563236  -0.70832205]
 [ 0.         -0.23627122 -1.335592   -0.69493614  0.66463536]
 [-0.          1.75124972 -0.12254228 -0.26853996  0.8134674 ]
 [-0.          0.84405862  0.03013241 -0.48867506 -1.53653601]
 [-0.         -0.3809699   0.7937492  -1.75475931  0.18403154]]
 
[[-1.3346739  -0.          0.         -0.         -0.        ]
 [ 1.11161753 -0.          0.          0.         -0.        ]
 [-0.42926086  0.         -0.          0.         -0.        ]
 [ 0.82880086  0.         -0.         -0.         -0.        ]
 [-0.33432961  0.          0.         -0.         -0.        ]]
