In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
MATRIX_SIZE = 4
matrix = np.random.randn(MATRIX_SIZE, MATRIX_SIZE)
print(matrix)

[[-0.28006069  1.74168605 -1.23018533 -2.87760313]
 [ 0.31847634 -1.14949898 -0.95965202 -0.76354709]
 [ 0.60193723 -0.57034825 -0.33270169  1.26359993]
 [-0.55773248 -0.07595528 -0.09834115 -0.15645113]]


In [29]:
Q = np.zeros((MATRIX_SIZE, MATRIX_SIZE))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
for i in range(MATRIX_SIZE):
    Q[:, i] = matrix[:, i]
    a = matrix[:, i]
    for j in range(i):
        q = Q[:, j]
        Q[:, i] = Q[:, i] - np.dot(a, q) / np.dot(q, q) * q
    Q[:, i] /= np.linalg.norm(Q[:, i])

print(Q)
print(Q @ np.linalg.inv(Q))

[[-0.30318849  0.77108426 -0.55900981  0.03184086]
 [ 0.34477655 -0.40656014 -0.76801256 -0.35495731]
 [ 0.65164603  0.13825918 -0.12079973  0.73596826]
 [-0.60379079 -0.4701301  -0.28822243  0.57562331]]
[[ 1.00000000e+00  1.23938269e-17 -1.30970122e-17  4.55752117e-17]
 [-1.56079376e-16  1.00000000e+00  3.96180442e-17  2.40408171e-18]
 [-9.61364123e-18 -1.73393751e-17  1.00000000e+00  1.64517835e-17]
 [ 6.14347215e-17  2.59617205e-17  1.35869960e-16  1.00000000e+00]]


In [31]:
QP, R = np.linalg.qr(matrix)

In [32]:
print( np.round( Q - QP ,10) ), print(' ')
print( np.round( Q + QP ,10) )

[[-0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [ 0.  0.  0.  0.]
 [-0.  0. -0.  0.]]
 
[[-0.60637698  1.54216852 -1.11801961  0.06368172]
 [ 0.6895531  -0.81312028 -1.53602512 -0.70991461]
 [ 1.30329205  0.27651836 -0.24159946  1.47193652]
 [-1.20758159 -0.94026021 -0.57644486  1.15124662]]
