In [1]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

In [3]:
rank = 4
matrix = np.random.randn(rank, rank)
print(matrix)

[[ 1.06404993 -0.85184036  0.73061284  0.12176272]
 [ 1.97352195 -0.45135616  0.39160262  0.12264993]
 [ 0.61957743 -0.64993161  2.09564979  0.71190445]
 [-1.81054384 -0.19774401  0.71648591 -0.14968797]]


In [7]:
P, L, U = scipy.linalg.lu(matrix)

In [9]:
matrix_inv = np.linalg.inv(U) @ np.linalg.inv(L) @ P.T
matrix_inv_test = np.round(matrix @ matrix_inv)
print(matrix_inv_test)

[[ 1.  0.  0.  0.]
 [-0.  1. -0.  0.]
 [ 0. -0.  1. -0.]
 [-0. -0.  0.  1.]]


In [10]:
matrix_inv_direct = np.linalg.inv(matrix)
print(matrix_inv)
print(matrix_inv_direct)

[[-0.46253985  0.88592037 -0.0471559   0.12537728]
 [-2.67425243  2.09686458  0.26535726  0.8047745 ]
 [-1.44449701  1.89242914  0.18992347  1.27884547]
 [ 2.2132997  -4.4274852   1.1288983  -3.13896729]]
[[-0.46253985  0.88592037 -0.0471559   0.12537728]
 [-2.67425243  2.09686458  0.26535726  0.8047745 ]
 [-1.44449701  1.89242914  0.18992347  1.27884547]
 [ 2.2132997  -4.4274852   1.1288983  -3.13896729]]
