In [4]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

In [5]:
A = np.random.randn(7, 4)

In [6]:
L = np.linalg.pinv(A.T @ A) @ A.T

In [7]:
AI = np.linalg.pinv(A)

In [8]:
print(np.round(L - AI, 5))

[[-0. -0. -0.  0.  0. -0. -0.]
 [ 0. -0.  0.  0. -0.  0.  0.]
 [-0. -0. -0.  0.  0.  0. -0.]
 [-0.  0. -0. -0. -0. -0.  0.]]


In [10]:
A = np.random.randn(4, 7)

In [11]:
R = A.T @ np.linalg.pinv(A @ A.T)

In [12]:
AI = np.linalg.pinv(A)

In [13]:
print(np.round(R - AI, 5))

[[-0.  0. -0.  0.]
 [ 0.  0.  0.  0.]
 [-0. -0.  0. -0.]
 [-0. -0. -0.  0.]
 [ 0.  0. -0.  0.]
 [ 0. -0.  0. -0.]
 [-0.  0. -0.  0.]]
