In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg
from scipy.linalg import toeplitz

In [5]:
A = np.diag([1,0,0,0,0])
print(np.linalg.matrix_rank(A), A)

B = np.diag([-1,0,0,0,0])
print(np.linalg.matrix_rank(B), B)

C = A+B
print(np.linalg.matrix_rank(C), C)

1 [[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1 [[-1  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
0 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
